### ISSUE TITLE
DAOHelper has a concurrency problem 

### ISSUE THREAD

**Issue by poolborges** [NOSiCode-CV/igrp-rest#25]
DAOHelper use single pattern, so the "private EntityManager em" is shared across all concurrent thread/request.

* Should create a EntityManager instance per thread/request.
* Should close the EntityManager instance after work done

**Comment by IMarcelF** [comment]
Ah yes ! 

We are trying to use Double-checked locking Singleton class ... but this pattern in not a very good solution when we are dealing with thread safe.

Create a EntityManager instance for each request ... we think that is a expensive processing because the hibernate creates a pool of connection for each new  EntityManager instance.

Maybe initialize the EntityManager using  EJB dependency injection @PersistenceUnit .. will resolve this problem ...

Anyway, we want share and change ideas with you to find out the best solution to solve this problem.

Thanks in advance !

**Comment by poolborges** [comment]
**1.** Is not the EntityManager that create a connection pool, but the EntityManagerFactory.

- EntityManagerFactory is created for each database and it is "same" to a connection pool
- EntityManagerFactory.createEntityManager(); return 1 connection from the pool.
- EntityManager.close();  release the connection to be available in connection pool

**2.**  Singleton Pattern
- In fact the current implementation of DAOHelper is "BAD/naive implementation of Singleton Pattern" and is not a implementation of "Singleton Pattern with Double-Checked Locking". 
- Singleton Pattern with Double-Checked Locking, and volatile (JLS >= 5)
- Singleton Pattern with Double-Checked Locking, and volatile (JLS >= 5)

**3.** Depend at Compile-time  only on JPA spec
- We can depend at compile-time only to JPA API and at run-time chose eclipselink or Hibernate(This is a very easy thing to do with the current code) 

**4.** Using EJB with this "small" application could be a "overkill", but is a powerful specification. 
- Declarative transaction(declarative) need something if the business case could be handle

**4.** For dependency injection we could use CDI (Context Dependency Injection) 

**6.** Look for microprofile.io offer a set of "de facto standards" (JAX-RS, CDI, Config, )

**7.** We can open a new issue to shared knowledge and discus the design and improvements  

ps: I have experience with those spec so i can help here. 

**Reference**
- https://www.ibm.com/developerworks/library/j-dcl/index.html
- https://en.wikipedia.org/wiki/Double-checked_locking
- http://microprofile.io/
-

**Comment by IMarcelF** [comment]
All right !

We will open a new issue to share knowledge and discus the design and improvements ...
